# Generated by Django 3.2 on 2022-05-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='业务员ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='客户ID')),
                ('customerName', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('customerType', models.SmallIntegerField(choices=[(1, '个人'), (2, '单位')], default=1, verbose_name='客户性质')),
                ('dicount', models.FloatField(verbose_name='折扣率')),
                ('contactName', models.CharField(max_length=12, verbose_name='联系人')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCar',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, verbose_name='车架号')),
                ('lpn', models.CharField(max_length=12, verbose_name='车牌号')),
                ('color', models.CharField(max_length=12, verbose_name='颜色')),
                ('carType', models.CharField(max_length=12, verbose_name='车型')),
                ('category', models.SmallIntegerField(choices=[(1, '微型车'), (2, '中型车'), (3, '大型车')], default=1, verbose_name='车辆类别')),
                ('status', models.SmallIntegerField(choices=[(1, '空闲'), (2, '正在维修')], default=1, verbose_name='状态')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.customer', verbose_name='客户ID')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='维修项目ID')),
                ('itemName', models.CharField(max_length=64, verbose_name='维修项目名称')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceMan',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='维修员ID')),
                ('mName', models.CharField(max_length=12, verbose_name='维修员姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('status', models.SmallIntegerField(choices=[(1, '空闲'), (2, '工作中'), (3, '请假')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='维修委托单号')),
                ('recordDate', models.DateField(auto_now_add=True, verbose_name='登记日期')),
                ('customerPhone', models.CharField(max_length=11, verbose_name='客户联系电话')),
                ('maintenanceType', models.SmallIntegerField(choices=[(1, '普通'), (2, '加急')], default=1, verbose_name='维修类型')),
                ('category', models.SmallIntegerField(choices=[(1, '小修'), (2, '中修'), (3, '大修')], default=1, verbose_name='作业分类')),
                ('payway', models.SmallIntegerField(choices=[(1, '自付'), (2, '三包'), (3, '进保')], default=1, verbose_name='结算方式')),
                ('mileage', models.IntegerField(verbose_name='进厂里程数')),
                ('oil', models.FloatField(verbose_name='进厂油量')),
                ('inDatetime', models.DateTimeField(verbose_name='进厂时间')),
                ('sName', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务员姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='业务员联系电话')),
                ('finishDatetime', models.DateField(blank=True, null=True, verbose_name='预计完工时间')),
                ('faultDiscribe', models.TextField(verbose_name='故障描述')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='维修总费用')),
                ('status', models.SmallIntegerField(choices=[(1, '待受理'), (2, '正在维修'), (3, '已完成维修')], default=1, verbose_name='状态')),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.customer', to_field='customerName', verbose_name='客户名称')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('workOrderId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='维修派工单ID')),
                ('recordDate', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('startTime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('hour', models.FloatField(verbose_name='工时')),
                ('status', models.SmallIntegerField(choices=[(1, '待开始'), (2, '进行中'), (3, '已完成')], default=1, verbose_name='状态')),
                ('artificialCost', models.FloatField(blank=True, null=True, verbose_name='人工费')),
                ('totalPartsCost', models.FloatField(blank=True, null=True, verbose_name='总材料费')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.maintenanceitem', verbose_name='维修项目ID')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.maintenanceman', verbose_name='维修员ID')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.maintenanceorder', verbose_name='维修委托单ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('partId', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='零件编号')),
                ('partName', models.CharField(max_length=64, verbose_name='零件名称')),
                ('partNumber', models.IntegerField(verbose_name='零件数量')),
                ('price', models.FloatField(verbose_name='零件单价')),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='业务员ID')),
                ('sName', models.CharField(max_length=32, verbose_name='业务员姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='工种ID')),
                ('typeName', models.CharField(max_length=64, verbose_name='工种名称')),
                ('price', models.FloatField(verbose_name='工时单价')),
            ],
        ),
        migrations.CreateModel(
            name='UseParts',
            fields=[
                ('nId', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='使用零件ID')),
                ('partNumber', models.IntegerField(verbose_name='零件数量')),
                ('partCost', models.FloatField(verbose_name='零件费')),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.parts', verbose_name='零件编号')),
                ('workOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.maintenanceworkorder', verbose_name='维修派工单ID')),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.salesman', verbose_name='业务员ID'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dammapp.salesman', verbose_name='业务员ID'),
        ),
        migrations.AddField(
            model_name='maintenanceorder',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.customercar', verbose_name='车架号'),
        ),
        migrations.AddField(
            model_name='maintenanceman',
            name='workType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dammapp.worktype', verbose_name='工种'),
        ),
    ]
